export const jsTypes = {
  array: "Array",
  bigint: "Number",
  bigserial: "Number",
  bit: "String",
  "bit varying": "String",
  boolean: "Boolean",
  box: "String",
  bytea: "String",
  character: "String",
  "character varying": "String",
  cidr: "String",
  circle: "String",
  citext: "String",
  date: "Date",
  "double precision": "Number",
  hstore: "Object",
  inet: "String",
  integer: "Number",
  interval: "String",
  json: "Object",
  jsonb: "Object",
  line: "String",
  lseg: "String",
  macaddr: "String",
  money: "Number",
  numeric: "Number",
  path: "String",
  point: "String",
  polygon: "String",
  real: "Number",
  smallint: "Number",
  smallserial: "Number",
  serial: "Number",
  text: "String",
  "time without time zone": "String",
  "time with time zone": "String",
  "timestamp without time zone": "Date",
  "timestamp with time zone": "Date",
  tsquery: "String",
  tsvector: "String",
  txid_snapshot: "String",
  uuid: "String",
  xml: "String",
  "user-defined": "String",
  int4range: "String",
  int8range: "String",
  numrange: "String",
  tsrange: "String",
  tstzrange: "String",
  daterange: "String",
};
